version: "3.8"

services:
  postgres:
    container_name: db_postgres
    image: postgis/postgis:16-3.5-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  nominatim:
    container_name: griha_bhoomi_nominatim
    image: mediagis/nominatim:5.3.2
    restart: unless-stopped
    environment:
      PBF_URL: https://download.geofabrik.de/asia/nepal-latest.osm.pbf
      REPLICATION_URL: https://download.geofabrik.de/asia/nepal-updates/
      NOMINATIM_PASSWORD: password123
    ports:
      - 8080:8080
    volumes:
      - nominatim-data:/var/lib/postgresql/16/main
    shm_size: 1gb

  adminer:
    container_name: adminer
    image: adminer:4.8.1
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: db_postgres
    ports:
      - 8085:8080

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: E:\databases\griha-bhoomi
