version: "3.8"

services:
  postgres:
    container_name: db_postgres
    image: postgres:16.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    container_name: adminer
    image: adminer:4.8.1
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: db_postgres
    ports:
      - 8085:8080

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: E:\databases\griha-bhoomi
