version: "3.8"

services:
  griha-bhoomi-backend:
    container_name: dev-griha-bhoomi-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./backend/.env.local
    ports:
      - 5000:5000
    networks:
      - griha-bhoomi
    volumes:
      - ./backend:/usr/src/app/backend
      - /usr/src/app/backend/node_modules
    command: pnpm run dev
    depends_on:
      - postgres

  postgres:
    container_name: db_postgres
    image: postgres:16.2-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - griha-bhoomi

  adminer:
    container_name: adminer
    image: adminer:4.8.1
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: db_postgres
    ports:
      - 8085:8080
    networks:
      - griha-bhoomi
    depends_on:
      - postgres

  redis:
    container_name: redis
    image: redis:7.2-alpine
    restart: unless-stopped
    env_file:
      - ./backend/.env.local
    ports:
      - 6379:6379
    networks:
      - griha-bhoomi

networks:
  griha-bhoomi:

volumes:
  backend:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: E:\databases\griha-bhoomi
