# Selecting base image
FROM node:26-alpine

RUN npm install -g pnpm@10.33.2

# Selecting Work directory
WORKDIR /usr/src/app

# Specifiying development environment
ENV NODE_ENV=development

# Copying the dependency file
COPY package.json pnpm-lock.yaml ./

# Installing the dependencies
RUN pnpm install

# Copying rest of the files
COPY . .

# Make a non-root user
#RUN adduser -D grihabhoomiuser && echo "grihabhoomiuser:MBrcFRcgHyM/gXTMBjL4CA==" | chpasswd

# Change to grihabhoomiuser
#USER grihabhoomiuser